FROM python:3.8-alpine

RUN mkdir /app

RUN apk add --update vim

RUN apk add py3-pip

RUN apk add build-base

RUN pip3 install kafka-python

#Instalando Dependencias
COPY ./requirements.txt .
RUN pip install -r requirements.txt
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
RUN pip install psycopg2
RUN pip install -U textblob
RUN python -m textblob.download_corpora
RUN python -m nltk.downloader stopwords

