FROM python:3.8-alpine

RUN mkdir /app
WORKDIR /app
RUN mkdir /nlkt_data
RUN apk add --update vim

RUN apk add py3-pip

RUN apk add build-base

RUN pip3 install kafka-python

#Instalando Dependencias

COPY ./requirements.txt .
RUN pip3 install -r requirements.txt
RUN apk update && apk add postgresql-dev gcc python3-dev musl-dev
RUN pip3 install psycopg2
RUN python -m textblob.download_corpora
RUN python3 -m nltk.downloader stopwords
COPY . /app
